import {
  ArrowRight,
  Bookmark,
  Check,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  Compass,
  ExternalLink,
  FlaskConical,
  Heart,
  History,
  Home,
  Image,
  KeyRound,
  Lightbulb,
  List,
  LogIn,
  Menu,
  MessageCircle,
  Minus,
  MoreHorizontal,
  Moon,
  PanelTop,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  UserRound,
  X,
  type LucideProps
} from "lucide-react";

export const iconMap = {
  arrow: ArrowRight,
  bookmark: Bookmark,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  help: CircleHelp,
  compass: Compass,
  external: ExternalLink,
  flask: FlaskConical,
  heart: Heart,
  history: History,
  home: Home,
  image: Image,
  key: KeyRound,
  lightbulb: Lightbulb,
  list: List,
  login: LogIn,
  menu: Menu,
  message: MessageCircle,
  minus: Minus,
  more: MoreHorizontal,
  moon: Moon,
  panel: PanelTop,
  plus: Plus,
  refresh: RefreshCw,
  reset: RotateCcw,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  sun: Sun,
  trash: Trash2,
  user: UserRound,
  x: X
} as const;

export type IconName = keyof typeof iconMap;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = iconMap[name];
  return <Component aria-hidden="true" {...props} />;
}
